# Generated by Django 5.2.11 on 2026-04-23 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTecnologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Tecnologia',
                'verbose_name_plural': 'Tipos de Tecnologias',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.tipotecnologia'),
        ),
    ]
